homeassistant:
  name: Domov
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Prague
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

#mobile_app:

frontend:
  themes: !include_dir_merge_named themes
config:
system_health:
http:

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

logger:
  default: info

# Discover some devices automatically
discovery:

# View all events in a logbook
logbook:

# Track the sun
sun:

smartir:
climate:
  - platform: smartir
    name: AC_bedroom
    unique_id: ac_bedroom
    device_code: 1402
    controller_data: remote.broadlink_bedroom_remote
  - platform: smartir
    name: AC_kids
    unique_id: ac_kids
    device_code: 1402
    controller_data: remote.broadlink_kids_remote
  - platform: smartir
    name: AC_living
    unique_id: ac_living
    device_code: 1402
    controller_data: remote.broadlink_living_remote

mqtt:
  discovery: true
  broker: 192.168.10.200
  certificate: /home/homeassistant/MQTTCAcert.pem
  client_id: homeassistant
  client_key: /home/homeassistant/MQTThassClient.key
  client_cert: /home/homeassistant/MQTThassClient.pem
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'


notify:
  - name: pushover
    platform: pushover
    api_key: !secret pushover_apikey
    user_key: !secret pushover_userkey


automation: !include automations.yaml

input_boolean: !include input/boolean.yaml
#input_select: !include input/select.yaml
input_number: !include input/number.yaml
input_datetime: !include input/datetime.yaml

alert: !include_dir_named alerts

sensor: !include_dir_list sensors
binary_sensor: !include_dir_list binary_sensors

# Enables support for tracking state changes over time
history:
# Tracked history is kept for 10 days
recorder:
  purge_interval: 1
# Store data to InfluxDB
influxdb:
  username: !secret influx_user
  password: !secret influx_password
  tags_attributes:
    - friendly_name
  exclude:
    domains:
      - automation

webhook:

zigbee2mqtt_networkmap:
   #topic: your topic (optional, default zigbee2mqtt)
panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    url: '/local/community/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'
