alias: Lights in bed - power off
description: ''
trigger:
  - entity_id: sensor.0x00158d0002030217_click
    platform: state
    to: double
  - entity_id: sensor.0x04cf8cdf3c7d4560_action
    platform: state
    to: button_3_hold
action:
  - service: light.turn_off
    entity_id: light.0x14b457fffe40d0c9_light
  - service: light.turn_off
    entity_id: light.0x14b457fffe3f6c2c_light

