alias: Lights in bed - Jarda min
description: ''
trigger:
  - entity_id: sensor.button_bedroom_action
    platform: state
    to: button_6_hold
action:
  - service: light.turn_on
    entity_id: light.lightbedroom_jarda_light
    data:
      brightness: 10
