alias: Lights in bed - power off
description: ''
trigger:
  - entity_id: sensor.button_xiaomi_click
    platform: state
    to: double
  - entity_id: sensor.button_bedroom_action
    platform: state
    to: button_3_hold
action:
  - service: light.turn_off
    entity_id: light.lightbedroom_jirka_light
  - service: light.turn_off
    entity_id: light.lightbedroom_jarda_light

