alias: Lights in bed - Jirka max
description: ''
trigger:
  - entity_id: sensor.button_bedroom_action
    platform: state
    to: button_1_hold
action:
  - service: light.turn_on
    entity_id: light.lightbedroom_jirka_light
    data:
      brightness: 254
