alias: Lights in bed - Jirka min
description: ''
trigger:
  - entity_id: sensor.0x04cf8cdf3c7d4560_action
    platform: state
    to: button_5_hold
  - entity_id: sensor.0x000d6f000e1b7ce1_action
    platform: state
    to: 'down_hold'
action:
  - service: light.turn_on
    entity_id: light.0x14b457fffe40d0c9_light
    data:
      brightness: 10
