alias: Lights in bed - Jardatoggle power
description: ''
trigger:
  - entity_id: sensor.0x04cf8cdf3c7d4560_action
    platform: state
    to: button_4_single
condition:
action:
  - service: light.toggle
    entity_id:
      - light.0x14b457fffe3f6c2c_light
