alias: Lights in bed - Jirka min
description: ''
trigger:
  - entity_id: sensor.button_bedroom_action
    platform: state
    to: button_5_hold
action:
  - service: light.turn_on
    entity_id: light.lightbedroom_jirka_light
    data:
      brightness: 10
