alias: Lights in bed - Jirka up
description: ''
trigger:
  - entity_id: sensor.button_bedroom_action
    platform: state
    to: button_1_single
action:
  - service: light.turn_on
    entity_id: light.lightbedroom_jirka_light
    data_template:
      brightness: >
        {% set suggested = states.light['lightbedroom_jirka_light'].attributes.brightness|int + 50 %}
        {% if suggested < 254 %}
        {{ suggested }}
        {% else %}
        254
        {% endif %}
