alias: Lights in bed - Jardatoggle power
description: ''
trigger:
  - entity_id: sensor.button_bedroom_action
    platform: state
    to: button_4_single
condition:
action:
  - service: light.toggle
    entity_id:
      - light.lightbedroom_jarda_light
