alias: Lights in bed - Jirka toggle power
description: ''
trigger:
  - entity_id: sensor.button_bedroom_action
    platform: state
    to: button_3_single
  - entity_id: sensor.0x04cf8cdf3c7d4560_action
    platform: state
    to: button_3_single
  - platform: mqtt
    topic: "zigbee2mqtt/Button_Bedroom"
    payload: "button_3_single"
    value_template: "{{ value_json.action }}"
condition:
action:
  - service: light.toggle
    entity_id:
      - light.lightbedroom_jirka_light
