alias: Lights in bed - Jirka down
description: ''
trigger:
  - entity_id: sensor.0x04cf8cdf3c7d4560_action
    platform: state
    to: button_5_single
action:
  - service: light.turn_on
    entity_id: light.0x14b457fffe40d0c9_light
    data_template:
      brightness: >
        {% set suggested = states.light['0x14b457fffe40d0c9_light'].attributes.brightness|int - 50 %}
        {% if suggested > 10 %}
        {{ suggested }}
        {% else %}
        10
        {% endif %}
