alias: Lights in bed - min both
description: ''
trigger:
  - entity_id: sensor.button_xiaomi_click
    platform: state
    to: hold
  - entity_id: sensor.button_bedroom_action
    platform: state
    to: button_4_hold
action:
  - service: light.turn_on
    entity_id:
      - light.lightbedroom_jarda_light
      - light.lightbedroom_jirka_light
    data:
      brightness: 10
