alias: Lights in bed - Jarda down
description: ''
trigger:
  - entity_id: sensor.button_bedroom_action
    platform: state
    to: button_6_single
action:
  - service: light.turn_on
    entity_id: light.lightbedroom_jarda_light
    data_template:
      brightness: >
        {% set suggested = states.light['lightbedroom_jarda_light'].attributes.brightness|int - 50 %}
        {% if suggested > 10 %}
        {{ suggested }}
        {% else %}
        10
        {% endif %}
