alias: Lights in bed - Jirka toggle power
description: ''
trigger:
  - entity_id: sensor.0x04cf8cdf3c7d4560_action
    platform: state
    to: button_3_single
condition:
action:
  - service: light.toggle
    entity_id:
      - light.0x14b457fffe40d0c9_light
