alias: 'Christmas lights - On'
trigger:
  - platform: time
    at: '16:30:00'
  - platform: time
    at: '6:30:00'
action:
  - service: switch.turn_on
    entity_id: switch.power_ac_living_switch
  - service: switch.turn_on
    entity_id: switch.power_ac_rooms_switch
mode: single