alias: 'Christmas lights - Off'
trigger:
  - platform: time
    at: '23:00:00'
  - platform: time
    at: '8:00:00'
action:
  - service: switch.turn_off
    entity_id: switch.0xccccccfffed72424_switch
  - service: switch.turn_off
    entity_id: switch.0xccccccfffed7291d_switch
mode: single