# Night light controlled by Sun movement
alias: Turn on night light at sunset
trigger:
  platform: sun
  event: sunset
action:
  service: switch.turn_on
  data:
    entity_id: switch.0x0017880108d870bc_switch
