esphome:
  name: vindriktning-co2
  # Turn on the LED at startup, pure white, no sensor indication yet
  on_boot:
    then:
      - light.turn_on:
          id: vindriktning_light
          brightness: 0.2
          red: 100%
          green: 100%
          blue: 100%

# Definition of ESP board (generic dev)
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable default logging
logger:

# Enable Home Assistant API
api:
  password: "XXXXXXX"

# Enable OTA FW upgrades
ota:
  password: "XXXXXXX"

# WiFi setup
wifi:
  ssid: "XXXXXXX"
  password: "XXXXXXX"
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Vindriktning CO2 Fallback Hotspot"
    password: "XXXXXXX"

# Enable fallback web UI
captive_portal:

# Enable I2C bus support
i2c:

# Enable UART bus support
uart:
  rx_pin: 16
  tx_pin: 17
  baud_rate: 9600

# Enable the RGB LEDs
light:
  - platform: neopixelbus
    type: GRB
    variant: 800KBPS
    pin: GPIO25
    num_leds: 3
    name: "Vindriktning LED"
    id: vindriktning_light

# Enable the fan
switch:
  - platform: gpio
    pin: 12
    name: "Vindriktning Fan"
    id: vindriktning_fan

# Define sensors and automations
sensor:
    # SCD41 sensor
  - platform: scd4x
    # CO2 value and automation
    co2:
      name: "Vindriktning CO2"
      id: vindriktning_sensor
      # On any value change evaluate and set the two upper LEDs
      # Different brightness values for day and night based on sun position.
      # 0-999 ppm Green, 1000-1999 ppm yellow, 2000+ ppm red
      on_value:
        then:
          - if:
              condition:
                and:
                   - sun.is_above_horizon:
                       elevation: -0.2236
                   - sensor.in_range:
                       id: vindriktning_sensor
                       below: 999.9999
              then:
                - light.addressable_set:
                    id: vindriktning_light
                    range_from: 1
                    range_to: 2
                    red: 0%
                    green: 100%
                    blue: 0%
                    color_brightness: 50%
          - if:
              condition:
                and:
                   - sun.is_below_horizon:
                       elevation: -0.2236
                   - sensor.in_range:
                       id: vindriktning_sensor
                       below: 999.9999
              then:
                - light.addressable_set:
                    id: vindriktning_light
                    range_from: 1
                    range_to: 2
                    red: 0%
                    green: 100%
                    blue: 0%
                    color_brightness: 20%

          - if:
              condition:
                and:
                   - sun.is_above_horizon:
                       elevation: -0.2236
                   - sensor.in_range:
                       id: vindriktning_sensor
                       above: 1000.0
                       below: 1999.9999
              then:
                - light.addressable_set:
                    id: vindriktning_light
                    range_from: 1
                    range_to: 2
                    red: 100%
                    green: 100%
                    blue: 0%
                    color_brightness: 50%
          - if:
              condition:
                and:
                   - sun.is_below_horizon:
                       elevation: -0.2236
                   - sensor.in_range:
                       id: vindriktning_sensor
                       above: 1000.0
                       below: 1999.9999
              then:
                - light.addressable_set:
                    id: vindriktning_light
                    range_from: 1
                    range_to: 2
                    red: 100%
                    green: 100%
                    blue: 0%
                    color_brightness: 20%

          - if:
              condition:
                and:
                   - sun.is_above_horizon:
                       elevation: -0.2236
                   - sensor.in_range:
                       id: vindriktning_sensor
                       above: 2000.0
              then:
                - light.addressable_set:
                    id: vindriktning_light
                    range_from: 1
                    range_to: 2
                    red: 100%
                    green: 0%
                    blue: 0%
                    color_brightness: 50%
          - if:
              condition:
                and:
                   - sun.is_below_horizon:
                       elevation: -0.2236
                   - sensor.in_range:
                       id: vindriktning_sensor
                       above: 2000.0
              then:
                - light.addressable_set:
                    id: vindriktning_light
                    range_from: 1
                    range_to: 2
                    red: 100%
                    green: 0%
                    blue: 0%
                    color_brightness: 20%

    # Temperature value
    temperature:
      name: "Vindriktning Temperature"
      filters:
        - offset: -5.0
    # Humidity value
    humidity:
      name: "Vindriktning Humidity"
    # Update the values every minute
    update_interval: 60s
    # IKEA built-in sensor of dust
  - platform: pm1006
    # PM2.5 value and automation
    pm_2_5:
      name: "Vindriktning PM2.5"
      id: vindriktning_pm25_sensor
      # On any value change evaluate and set the bottom LED
      # Different brightness values for day and night based on sun position.
      # 0-12 mg Green, 13-25 mg yellow, 26+ mg red
      on_value:
        then:
          - if:
              condition:
                and:
                   - sun.is_above_horizon:
                       elevation: -0.2236
                   - sensor.in_range:
                       id: vindriktning_pm25_sensor
                       below: 12
              then:
                - light.addressable_set:
                    id: vindriktning_light
                    range_from: 0
                    range_to: 0
                    red: 0%
                    green: 100%
                    blue: 0%
                    color_brightness: 50%
          - if:
              condition:
                and:
                   - sun.is_below_horizon:
                       elevation: -0.2236
                   - sensor.in_range:
                       id: vindriktning_pm25_sensor
                       below: 12
              then:
                - light.addressable_set:
                    id: vindriktning_light
                    range_from: 0
                    range_to: 0
                    red: 0%
                    green: 100%
                    blue: 0%
                    color_brightness: 20%

          - if:
              condition:
                and:
                   - sun.is_above_horizon:
                       elevation: -0.2236
                   - sensor.in_range:
                       id: vindriktning_pm25_sensor
                       above: 13
                       below: 25
              then:
                - light.addressable_set:
                    id: vindriktning_light
                    range_from: 0
                    range_to: 0
                    red: 100%
                    green: 100%
                    blue: 0%
                    color_brightness: 50%
          - if:
              condition:
                and:
                   - sun.is_below_horizon:
                       elevation: -0.2236
                   - sensor.in_range:
                       id: vindriktning_pm25_sensor
                       above: 13
                       below: 25
              then:
                - light.addressable_set:
                    id: vindriktning_light
                    range_from: 0
                    range_to: 0
                    red: 100%
                    green: 100%
                    blue: 0%
                    color_brightness: 20%

          - if:
              condition:
                and:
                   - sun.is_above_horizon:
                       elevation: -0.2236
                   - sensor.in_range:
                       id: vindriktning_pm25_sensor
                       above: 26
              then:
                - light.addressable_set:
                    id: vindriktning_light
                    range_from: 0
                    range_to: 0
                    red: 100%
                    green: 0%
                    blue: 0%
                    color_brightness: 50%
          - if:
              condition:
                and:
                   - sun.is_below_horizon:
                       elevation: -0.2236
                   - sensor.in_range:
                       id: vindriktning_pm25_sensor
                       above: 26
              then:
                - light.addressable_set:
                    id: vindriktning_light
                    range_from: 0
                    range_to: 0
                    red: 100%
                    green: 0%
                    blue: 0%
                    color_brightness: 20%
    # Update the values every minute
    update_interval: 60s

# Configure the time and NTP
time:
  - platform: sntp
    id: sntp_time
    servers:
      - tik.cesnet.cz
      - tak.cesnet.cz
    timezone: Europe/Prague
    update_interval: 60min
    # Define automation for the PM2.5 fan (turn on once in 10 minutes)
    on_time:
      - seconds: 0
        minutes: /10
        then:
          - switch.turn_on: vindriktning_fan
      - seconds: 55
        minutes: /10
        then:
          - switch.turn_off: vindriktning_fan

# Configure location for sun position computation
sun:
  latitude: 50.00000°
  longitude: 14.00000°
